vouch:
  logLevel: debug
  domains:
    - Uri: example.com
      Service: test_service

  teamWhitelist:
    - "org1/team1"
    - "org1/team2"

  jwt:
    secret: testingsecret

oauth:
  Services:
    - id: test_service
      provider: github
      client_id: fake
      auth_url: fake
      callback_url: http://vouch.github.io:9090/auth
