vouch:
  domains:
    - Uri: example.com
      Service: test_service

  cookie:
    secure: false

  jwt:
    secret: testingsecret

  post_logout_redirect_uris:
    - http://myapp.example.com/login
    # https://accounts.google.com/.well-known/openid-configuration
    - https://oauth2.googleapis.com/revoke

oauth:
  Services:
    - id: test_service
      provider: google
      client_id: http://vouch.github.io
      auth_url: https://indielogin.com/auth
      callback_url: http://vouch.github.io:9090/auth
      end_session_endpoint: https://indielogin.com/logout
