vouch:
  logLevel: debug
  
  case_insensitive_emails: true

  whiteList:
    # these should work if cases do not match with incoming email
    - test@example.com
    - test@sub.example.com
    - test_username

  jwt:
    secret: testingsecret

oauth:
  provider: indieauth
  client_id: http://vouch.github.io
  auth_url: https://indielogin.com/auth
  callback_url: http://vouch.github.io:9090/auth
